import Head from 'next/head'
import Header from '../components/Header'
import Nav from '../components/Nav'
import Results from '../components/Results'
import requests from '../utils/request'


export default function Home({results}) {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://cdn.iconscout.com/icon/free/png-256/google-play-movies-tv-2038775-1721662.png" />
      </Head>
      <Header/>
      <Nav/>
      <Results  results={results}/>
    </div>
  )
}

export async function getServerSideProps(context){
  const genre = context.query.genre;

  const request = await fetch(`https://api.themoviedb.org/3${requests[genre]?.url || 
request.fetchTrending.url}`).then(res => res.json())

return {
  props:{
    results:request.results,
  }
}
}